#!/bin/bash
#  build_jshon .. a script to untar and build jshon static.
#  rob@vastdata.com


which gcc >/dev/null 2>&1 || echo you need to run the following to get gcc and other tools
which gcc >/dev/null 2>&1 || echo sudo apt install -y build-essential
which gcc || exit


wget http://digip.org/jansson/releases/jansson-2.13.tar.gz

tar xzvf jansson-2.13.tar.gz && cd jansson-2.13
./configure --enable-static && make && cp src/.libs/libjansson.a ..
cd ..

wget http://kmkeen.com/jshon/jshon.tar.gz

tar xzf jshon.tar.gz && cd jshon-20120914  && cp ../libjansson.a ./
cp ../jansson-2.13/src/jan*.h ./
sed -i -e 's/-ljansson/libjansson.a/'  Makefile
sed -i -e 's/-std=c99 -Wall/-std=c99 -O3 -Wall/'  Makefile
sed -i -e 's/<jansson.h>/"jansson.h"/g' jshon.c
make
rm -f ../jshon
strip jshon
cp jshon ..

echo "Note.. we also need python3 to post-process json"
