{
 "title": "Client ECN stats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "mlx5 client stats  Bytes/sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(mlx5_port_rcv_data_total [2m])  >0  ",
     "legendFormat": "IN instance={{instance}}  device={{device}}"
    },
    {
     "expr": "irate(mlx5_port_xmit_data_total[2m])  >0",
     "legendFormat": "OUT instance={{instance}}  device={{device}}"
    }
   ]
  },
  {
   "title": "ECN stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "irate(mlx5_np_cnp_sent_total{}[2m])  >0  ",
     "legendFormat": "CNP_sent{{instance}}   device={{device}}  port{{port}}"
    },
    {
     "expr": "irate(mlx5_rp_cnp_handled_total{}[2m])  >0",
     "legendFormat": "CNP_handled{{instance}}   device={{device}}  port{{port}}"
    },
    {
     "expr": "irate(mlx5_np_ecn_marked_roce_packets_total{}[2m])  >0",
     "legendFormat": "NP_ecn_Marked {{instance}}   device={{device}}  port{{port}}"
    }
   ]
  },
  {
   "title": "Switch port pause packets per second",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(switch_port_pause_packets_total[2m])  >0"
    },
    {}
   ]
  },
  {
   "title": "Switch port pause packets per second",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(switch_port_pause_packets_total[2m])  >0"
    },
    {}
   ]
  },
  {
   "title": "Client PFC QOS   RX   packets (prio 0 and prio 3)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_net_ethtool{device=\"enp94s0f1\",type=\"rx_prio3_packets\"} [2m])  >0"
    },
    {
     "expr": "irate(node_net_ethtool{device=\"enp94s0f1\",type=\"rx_prio0_packets\"} [2m])  >0"
    },
    {
     "expr": "irate(node_net_ethtool{device=\"enp94s0f1\",type=\"rx_prio0_pause\"} [2m])  >0"
    },
    {
     "expr": "irate(node_net_ethtool{device=\"enp94s0f1\",type=\"rx_prio3_pause\"} [2m])  >0"
    }
   ]
  },
  {
   "title": "Client PFC QOS   TX   packets (prio3 and prio 0)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_net_ethtool{device=\"enp94s0f1\",type=\"tx_prio3_packets\"} [2m])  >0"
    },
    {
     "expr": "irate(node_net_ethtool{device=\"enp94s0f1\",type=\"tx_prio0_packets\"} [2m])  >0"
    },
    {
     "expr": "irate(node_net_ethtool{device=\"enp94s0f1\",type=\"tx_prio0_pause\"} [2m])  >0"
    },
    {
     "expr": "irate(node_net_ethtool{device=\"enp94s0f1\",type=\"tx_prio3_pause\"} [2m])  >0"
    }
   ]
  },
  {
   "title": "Client PFC QOS   RX   PFC  pauses",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_net_ethtool{device=\"enp94s0f1\",type=\"rx_prio3_pause\"} [2m])  >0"
    },
    {
     "expr": "irate(node_net_ethtool{device=\"enp94s0f1\",type=\"rx_prio0_pause\"} [2m])  >0"
    },
    {
     "expr": "irate(node_net_ethtool{device=\"enp94s0f1\",type=\"rx_prio0_pause\"} [2m])  >0"
    },
    {
     "expr": "irate(node_net_ethtool{device=\"enp94s0f1\",type=\"rx_prio3_pause\"} [2m])  >0"
    }
   ]
  },
  {
   "title": "Client RDMA  traffic",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_net_ethtool{device=\"enp94s0f1\",type=\"rx_vport_rdma_unicast_bytes\"}[2m])  >0"
    },
    {
     "expr": "irate(node_net_ethtool{device=\"enp94s0f1\",type=\"tx_vport_rdma_unicast_bytes\"} [2m])  >0"
    }
   ]
  }
 ]
}