{
 "title": "se-demo Overview",
 "description": "dashboaard for IO capacity benchmarks",
 "time": { "from": "2019-10-26T18:46:54.031Z", "to": "2019-10-26T19:48:30.359Z" },
 "panels": [
  {
   "title": "VAST Cluster Bandwidth and Latency",
   "type": "graph",
   "description": "These are scraped from the json api and put into graphite.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "MBs", "label": "Bandwidth" }
   ],
   "targets": [
    { "target": "vast.*.rd_bw" },
    { "target": "vast.*.wr_bw" },
    { "target": "vast.*.latency" }
   ]
  },
  {
   "title": "VAST Cluster IOPS and Latency",
   "type": "graph",
   "description": "These are scraped from the json api and put into graphite.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "IOPS" }
   ],
   "targets": [
    { "target": "vast.*.iops" },
    { "target": "vast.*.latency" }
   ]
  },
  {
   "title": "VAST Cluster read and write Latency",
   "type": "graph",
   "description": "These are scraped from the json api and put into graphite.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms", "label": "Latency (ms)" }
   ],
   "targets": [
    { "target": "vast.*.rd_latency" },
    { "target": "vast.*.wr_latency" }
   ]
  },
  {
   "title": "XDD read rates",
   "type": "graph",
   "description": "this are the xdd read rates reported from xdd_mehere in trmb_raidtests.\ndirectio is enabled",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    { "target": "ioblast.se-demo*.xdd.read.rate" }
   ]
  },
  {
   "title": "XDD write rates",
   "type": "graph",
   "description": "this are the xdd write rates reported from xdd_mehere in trmb_raidtests",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "target": "ioblast.se-demo*.xdd.write.rate"
    }
   ]
  },
  {
   "title": "ioblast seconds",
   "type": "graph",
   "description": "how many seconds ioblast completes in.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "target": "ioblast.se-demo*.ioblast" }
   ]
  },
  {
   "title": "Fileop creates per second",
   "type": "graph",
   "description": "how many creates per second in fileop",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "ioblast.se-demo*.fileop.create" }
   ]
  },
  {
   "title": "Fileop deletes per second",
   "type": "graph",
   "description": "how many deletes per second in fileop",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "ioblast.se-demo*.fileop.delete" }
   ]
  },
  {
   "title": "Fileop seconds",
   "type": "graph",
   "description": "how many seconds fileop completes in.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "ioblast.se-demo*.fileop.seconds"
    }
   ]
  },
  {
   "title": "xdd_mehere_overall time",
   "type": "graph",
   "description": "this are the xdd write rates reported from xdd_mehere in trmb_raidtests",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "ioblast.se-demo*.overall.seconds"
    },
    {
     "target": "canary.filer.*.client.*.percentused"
    }
   ]
  },
  {
   "title": "ioblast canary times",
   "type": "graph",
   "description": "this are the xdd write rates reported from xdd_mehere in trmb_raidtests",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "target": "canary.filer.10_101_12*" },
    {
     "target": "canary.filer.*.client.*.percentused"
    }
   ]
  },
  {
   "title": "xdd_mehere_overall retransmits per second",
   "type": "graph",
   "description": "this are the TCP retransmission per second",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "ioblast.se-demo*.overall.retranspersec"
    },
    {
     "target": "canary.filer.*.client.*.percentused"
    }
   ]
  }
 ]
}