{
 "title": "VAST Cluster Performance",
 "description": "dashboaard for VAST metrics scraped from the API",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": "vast.*" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "options": {
    "content": "<a href=\"https://vastdata.com\">\n\t\t\t\t\t\t\t\t\t\t\t\t\t<img data-rjs=\"2\" src=\"https://uploads.vastdata.com/2020/04/logo.svg\" alt=\"logo\" />\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t</a>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 0 },
   "options": {
    "content": "<a href=\"https://vastdata.com\">\n\t\t\t\t\t\t\t\t\t\t\t\t\t<img data-rjs=\"2\" src=\"https://uploads.vastdata.com/2020/04/logo.svg\" alt=\"logo\" />\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t</a>\n"
   }
  },
  {
   "title": "VAST Cluster Bandwidth",
   "type": "graph",
   "description": "These are scraped from the json api and put into graphite.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "MBs", "label": "Bandwidth" }
   ],
   "targets": [
    {
     "target": "vast.$cluster.ProtoCommon.rd_bw"
    },
    {
     "target": "vast.$cluster.ProtoCommon.wr_bw"
    }
   ]
  },
  {
   "title": "VAST Cluster IOPS and Latency",
   "type": "graph",
   "description": "These are scraped from the json api and put into graphite.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "IOPS" }
   ],
   "targets": [
    {
     "target": "vast.$cluster.ProtoCommon.rd_iops"
    },
    {
     "target": "vast.$cluster.ProtoCommon.wr_iops"
    }
   ]
  },
  {
   "title": "VAST Cluster read and write Latency",
   "type": "graph",
   "description": "These are scraped from the json api and put into graphite.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ms", "label": "Latency (ms)" }
   ],
   "targets": [
    {
     "target": "vast.$cluster.ProtoCommon.rd_latency"
    },
    {
     "target": "vast.$cluster.ProtoCommon.wr_latency"
    }
   ]
  },
  {
   "title": "VAST Cluster Metadata IOPS",
   "type": "graph",
   "description": "These are scraped from the json api and put into graphite.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "IOPS" }
   ],
   "targets": [
    {
     "target": "vast.$cluster.ProtoCommon.rd_md_iops"
    },
    {
     "target": "scale(vast.$cluster.ProtoCommon.wr_md_iops, -1)"
    }
   ]
  },
  {
   "title": "VAST Cluster Storage Capacity",
   "type": "graph",
   "description": "These are scraped from the json api and put into graphite.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "dectbytes", "label": "Space (TB)" }
   ],
   "targets": [
    {
     "target": "vast.$cluster.Capacity.physical_space_in_use"
    },
    {
     "target": "vast.$cluster.Capacity.physical_space"
    },
    {
     "target": "vast.$cluster.Capacity.logical_space"
    },
    {
     "target": "vast.$cluster.Capacity.logical_space_in_use"
    }
   ]
  },
  {
   "title": "VAST Cluster Storage Capacity",
   "type": "graph",
   "description": "These are scraped from the json api and put into graphite.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "dectbytes", "label": "Space (TB)" }
   ],
   "targets": [
    {
     "target": "vast.$cluster.Capacity.physical_space_in_use"
    },
    {
     "target": "vast.$cluster.Capacity.physical_space"
    },
    {
     "target": "vast.$cluster.Capacity.logical_space"
    },
    {
     "target": "vast.$cluster.Capacity.logical_space_in_use"
    }
   ]
  },
  {
   "title": "VAST Top N: bandwidth by view",
   "type": "graph",
   "description": "These are scraped from the json api and put into graphite.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "MBs", "label": "Bytes / second" }
   ],
   "targets": [
    {
     "target": "vast.$cluster.topn.view.bw.read.*"
    },
    {
     "target": "vast.$cluster.topn.view.bw.write.*"
    }
   ]
  },
  {
   "title": "VAST Top N: bandwidth by Client",
   "type": "graph",
   "description": "These are scraped from the json api and put into graphite.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "MBs", "label": "Bytes / second" }
   ],
   "targets": [
    {
     "target": "vast.$cluster.topn.client.bw.read.*"
    },
    {
     "target": "vast.$cluster.topn.client.bw.write.*"
    }
   ]
  },
  {
   "title": "VAST Top N: bandwidth by user",
   "type": "graph",
   "description": "These are scraped from the json api and put into graphite.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "binBps", "label": "Bytes / second" }
   ],
   "targets": [
    {
     "target": "vast.$cluster.topn.user.bw.read.*"
    },
    {
     "target": "vast.$cluster.topn.user.bw.write.*"
    }
   ]
  },
  {
   "title": "VAST Top N: Metadata IOPS by user",
   "type": "graph",
   "description": "These are scraped from the json api and put into graphite.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "binBps", "label": "Bytes / second" }
   ],
   "targets": [
    {
     "target": "vast.$cluster.topn.client.md_iops.read.*"
    },
    {
     "target": "vast.$cluster.topn.client.md_iops.write.*"
    }
   ]
  }
 ]
}