{
 "title": "VAST_Cluster_Stats_prom",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "2m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(vast_cluster_online, cluster)"
    }
   },
   {
    "name": "view",
    "query": {
     "query": "vast_view_logical_capacity{cluster=\"${cluster}\",path!~\"(/|/test-bucket.*)\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Notes",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<a href=\"https://vastdata.com\">\n\t<img data-rjs=\"2\" src=\"https://vastdata.com/vast-blue.png\" alt=\"logo\"\twidth=\"300px\", height=auto />\n</a>\n\n- #### URL to system management interface [https://$cluster-mgmt](https://$cluster-mgmt)\n- #### Per-view capacity information is accurate.\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Capacity Used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vast_cluster_physical_space_in_use{cluster=\"$cluster\"} / vast_cluster_physical_space{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Data Reduction Ratio",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vast_cluster_drr{cluster=\"$cluster\"}",
     "legendFormat": "Data Reduction Ratio"
    }
   ]
  },
  {
   "title": "Active S3 Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vast_cluster_metrics_ProtoConnectionMetrics_s3_conn_pool{cluster=\"$cluster\"}",
     "legendFormat": "S3 Connections"
    }
   ]
  },
  {
   "title": "Active NFS Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vast_cluster_metrics_ProtoConnectionMetrics_nfs3_tcp_pool{cluster=\"$cluster\"}",
     "legendFormat": "NFS Connections"
    }
   ]
  },
  {
   "title": "Cluster State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vast_cluster_online{cluster=\"$cluster\"}",
     "legendFormat": "Cluster State"
    }
   ]
  },
  {
   "title": "NVRAM Raid State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vast_nvram_raid_healthy{cluster=\"$cluster\"}",
     "legendFormat": "NVRAM State"
    }
   ]
  },
  {
   "title": "SSD Raid State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vast_ssd_raid_healthy{cluster=\"$cluster\"}",
     "legendFormat": "SSD State"
    }
   ]
  },
  {
   "title": "Memory Raid State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vast_memory_raid_healthy{cluster=\"$cluster\"}",
     "legendFormat": "Memory State"
    }
   ]
  },
  {
   "title": "Overall System Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(vast_cluster_metrics_ProtoMetrics_read_size_sum{cluster=\"$cluster\",proto_name=\"ProtoAll\"}[$__rate_interval])",
     "legendFormat": "Read"
    },
    {
     "expr": "rate(vast_cluster_metrics_ProtoMetrics_write_size_sum{cluster=\"$cluster\",proto_name=\"ProtoAll\"}[$__rate_interval])",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "I/O Operations/sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(vast_cluster_metrics_ProtoMetrics_read_size_count{cluster=\"$cluster\",proto_name=\"ProtoAll\"}[$__rate_interval])",
     "legendFormat": "Read"
    },
    {
     "expr": "rate(vast_cluster_metrics_ProtoMetrics_write_size_count{cluster=\"$cluster\",proto_name=\"ProtoAll\"}[$__rate_interval])",
     "legendFormat": "Write"
    },
    {
     "expr": "vast_cluster_metrics_ProtoMetrics_md_iops{cluster=\"$cluster\",proto_name=\"ProtoAll\"}",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "Average I/O Operation Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(vast_cluster_metrics_ProtoMetrics_read_size_sum{cluster=\"$cluster\",proto_name=\"ProtoAll\"}[$__rate_interval]) / rate(vast_cluster_metrics_ProtoMetrics_read_size_count{cluster=\"$cluster\",proto_name=\"ProtoAll\"}[$__rate_interval])",
     "legendFormat": "Read"
    },
    {
     "expr": "rate(vast_cluster_metrics_ProtoMetrics_write_size_sum{cluster=\"$cluster\",proto_name=\"ProtoAll\"}[$__rate_interval]) / rate(vast_cluster_metrics_ProtoMetrics_write_size_count{cluster=\"$cluster\",proto_name=\"ProtoAll\"}[$__rate_interval])",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Average I/O Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(vast_cluster_metrics_ProtoMetrics_read_latency_sum{cluster=\"$cluster\",proto_name=\"S3Common\"}[$__rate_interval]) / rate(vast_cluster_metrics_ProtoMetrics_read_latency_count{cluster=\"$cluster\",proto_name=\"S3Common\"}[$__rate_interval])",
     "legendFormat": "S3 Read Latency"
    },
    {
     "expr": "rate(vast_cluster_metrics_ProtoMetrics_write_latency_sum{cluster=\"$cluster\",proto_name=\"S3Common\"}[$__rate_interval]) / rate(vast_cluster_metrics_ProtoMetrics_write_latency_count{cluster=\"$cluster\",proto_name=\"S3Common\"}[$__rate_interval])",
     "legendFormat": "S3 Write Latency"
    },
    {
     "expr": "rate(vast_cluster_metrics_ProtoMetrics_read_latency_sum{cluster=\"$cluster\",proto_name=\"NFSCommon\"}[$__rate_interval]) / rate(vast_cluster_metrics_ProtoMetrics_read_latency_count{cluster=\"$cluster\",proto_name=\"NFSCommon\"}[$__rate_interval])",
     "legendFormat": "NFS Read Latency"
    },
    {
     "expr": "rate(vast_cluster_metrics_ProtoMetrics_write_latency_sum{cluster=\"$cluster\",proto_name=\"NFSCommon\"}[$__rate_interval]) / rate(vast_cluster_metrics_ProtoMetrics_write_latency_count{cluster=\"$cluster\",proto_name=\"NFSCommon\"}[$__rate_interval])",
     "legendFormat": "NFS Write Latency"
    },
    {
     "expr": "rate(vast_cluster_metrics_ProtoMetrics_read_latency_sum{cluster=\"$cluster\",proto_name=\"ProtoAll\"}[$__rate_interval]) / rate(vast_cluster_metrics_ProtoMetrics_read_latency_count{cluster=\"$cluster\",proto_name=\"ProtoAll\"}[$__rate_interval])",
     "legendFormat": "Overall Read Latency"
    },
    {
     "expr": "rate(vast_cluster_metrics_ProtoMetrics_write_latency_sum{cluster=\"$cluster\",proto_name=\"ProtoAll\"}[$__rate_interval]) / rate(vast_cluster_metrics_ProtoMetrics_write_latency_count{cluster=\"$cluster\",proto_name=\"ProtoAll\"}[$__rate_interval])",
     "legendFormat": "Overall Write Latency"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "timeseries",
   "description": "Auxiliary is snapshot space used + pending deletes",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "vast_cluster_physical_space{cluster=\"$cluster\"}",
     "legendFormat": "Physical Capacity"
    },
    {
     "expr": "vast_cluster_physical_space_in_use{cluster=\"$cluster\"}",
     "legendFormat": "Physical Used"
    },
    {
     "expr": "vast_cluster_logical_space_in_use{cluster=\"$cluster\"}",
     "legendFormat": "Logical Used"
    },
    {
     "expr": "vast_cluster_auxiliary_space_in_use{cluster=\"$cluster\"}",
     "legendFormat": "Auxiliary Used"
    }
   ]
  },
  {
   "title": "Data Reduction Ratio",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vast_cluster_drr{cluster=\"$cluster\"}",
     "legendFormat": "Data Reduction Ratio"
    }
   ]
  },
  {
   "title": "Active Client Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "vast_cluster_metrics_ProtoConnectionMetrics_s3_conn_pool{cluster=\"$cluster\"}",
     "legendFormat": "S3 Connections"
    },
    {
     "expr": "vast_cluster_metrics_ProtoConnectionMetrics_nfs3_tcp_pool{cluster=\"$cluster\"}",
     "legendFormat": "NFS Connections"
    }
   ]
  },
  {
   "title": "Per-User Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Throughput per User",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "vast_user_read_bw{cluster=\"$cluster\"} != 0",
       "legendFormat": "{{name}} - Read"
      },
      {
       "expr": "vast_user_write_bw{cluster=\"$cluster\"} != 0",
       "legendFormat": "{{name}} - Write"
      }
     ]
    },
    {
     "title": "I/O Operations/sec per User",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "vast_user_read_iops{cluster=\"$cluster\"} > 0.5",
       "legendFormat": "{{name}} - Read"
      },
      {
       "expr": "vast_user_write_iops{cluster=\"$cluster\"}  > 0.5",
       "legendFormat": "{{name}} - Write"
      },
      {
       "expr": "vast_user_md_iops{cluster=\"$cluster\"}  > 0.5",
       "legendFormat": "{{name}} - Other"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance Metrics per Cnode",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Throughput per Cnode",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(vast_cnode_metrics_ProtoMetrics_read_size_sum{cluster=\"$cluster\",proto_name=\"ProtoAll\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - Read"
      },
      {
       "expr": "rate(vast_cnode_metrics_ProtoMetrics_write_size_sum{cluster=\"$cluster\",proto_name=\"ProtoAll\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - Write"
      }
     ]
    },
    {
     "title": "I/O Operations/sec per Cnode",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(vast_cnode_metrics_ProtoMetrics_read_size_count{cluster=\"$cluster\",proto_name=\"ProtoAll\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - Read"
      },
      {
       "expr": "rate(vast_cnode_metrics_ProtoMetrics_write_size_count{cluster=\"$cluster\",proto_name=\"ProtoAll\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - Write"
      },
      {
       "expr": "vast_cnode_metrics_ProtoMetrics_md_iops{cluster=\"$cluster\",proto_name=\"ProtoAll\"}",
       "legendFormat": "{{hostname}} - Other"
      }
     ]
    },
    {
     "title": "Average I/O Operation Size per Cnode",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(vast_cnode_metrics_ProtoMetrics_read_size_sum{cluster=\"$cluster\",proto_name=\"ProtoAll\"}[$__rate_interval]) / rate(vast_cnode_metrics_ProtoMetrics_read_size_count{cluster=\"$cluster\",proto_name=\"ProtoAll\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - Read"
      },
      {
       "expr": "rate(vast_cnode_metrics_ProtoMetrics_write_size_sum{cluster=\"$cluster\",proto_name=\"ProtoAll\"}[$__rate_interval]) / rate(vast_cnode_metrics_ProtoMetrics_write_size_count{cluster=\"$cluster\",proto_name=\"ProtoAll\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - Write"
      }
     ]
    },
    {
     "title": "Average I/O Latency per Cnode",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rate(vast_cnode_metrics_ProtoMetrics_read_latency_sum{cluster=\"$cluster\",proto_name=\"ProtoAll\"}[$__rate_interval]) / rate(vast_cnode_metrics_ProtoMetrics_read_latency_count{cluster=\"$cluster\",proto_name=\"ProtoAll\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - Read Latency"
      },
      {
       "expr": "rate(vast_cnode_metrics_ProtoMetrics_write_latency_sum{cluster=\"$cluster\",proto_name=\"ProtoAll\"}[$__rate_interval]) / rate(vast_cnode_metrics_ProtoMetrics_write_latency_count{cluster=\"$cluster\",proto_name=\"ProtoAll\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - Write Latency"
      }
     ]
    },
    {
     "title": "Active S3 Client Connections per Cnode",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "vast_cnode_metrics_ProtoConnectionMetrics_s3_conn_pool{cluster=\"$cluster\"}",
       "legendFormat": "{{hostname}} - S3 Connections"
      }
     ]
    },
    {
     "title": "Active NFS Client Connections per Cnode",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 51 },
     "targets": [
      {
       "expr": "vast_cnode_metrics_ProtoConnectionMetrics_nfs3_tcp_pool{cluster=\"$cluster\"}",
       "legendFormat": "{{hostname}} - NFS Connections"
      }
     ]
    }
   ]
  },
  {
   "title": "S3 Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Throughput for S3",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(vast_cluster_metrics_ProtoMetrics_read_size_sum{cluster=\"$cluster\",proto_name=\"S3Common\"}[$__rate_interval])",
       "legendFormat": "Read"
      },
      {
       "expr": "rate(vast_cluster_metrics_ProtoMetrics_write_size_sum{cluster=\"$cluster\",proto_name=\"S3Common\"}[$__rate_interval])",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "I/O Operations/sec for S3",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(vast_cluster_metrics_ProtoMetrics_read_size_count{cluster=\"$cluster\",proto_name=\"S3Common\"}[$__rate_interval])",
       "legendFormat": "Read"
      },
      {
       "expr": "rate(vast_cluster_metrics_ProtoMetrics_write_size_count{cluster=\"$cluster\",proto_name=\"S3Common\"}[$__rate_interval])",
       "legendFormat": "Write"
      },
      {
       "expr": "vast_cluster_metrics_ProtoMetrics_md_iops{cluster=\"$cluster\",proto_name=\"S3Common\"}",
       "legendFormat": "Other"
      }
     ]
    },
    {
     "title": "Average I/O Operation Size for S3",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(vast_cluster_metrics_ProtoMetrics_read_size_sum{cluster=\"$cluster\",proto_name=\"S3Common\"}[$__rate_interval]) / rate(vast_cluster_metrics_ProtoMetrics_read_size_count{cluster=\"$cluster\",proto_name=\"S3Common\"}[$__rate_interval])",
       "legendFormat": "Read"
      },
      {
       "expr": "rate(vast_cluster_metrics_ProtoMetrics_write_size_sum{cluster=\"$cluster\",proto_name=\"S3Common\"}[$__rate_interval]) / rate(vast_cluster_metrics_ProtoMetrics_write_size_count{cluster=\"$cluster\",proto_name=\"S3Common\"}[$__rate_interval])",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "Average I/O Latency for S3",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rate(vast_cluster_metrics_ProtoMetrics_read_latency_sum{cluster=\"$cluster\",proto_name=\"S3Common\"}[$__rate_interval]) / rate(vast_cluster_metrics_ProtoMetrics_read_latency_count{cluster=\"$cluster\",proto_name=\"S3Common\"}[$__rate_interval])",
       "legendFormat": "Read Latency"
      },
      {
       "expr": "rate(vast_cluster_metrics_ProtoMetrics_write_latency_sum{cluster=\"$cluster\",proto_name=\"S3Common\"}[$__rate_interval]) / rate(vast_cluster_metrics_ProtoMetrics_write_latency_count{cluster=\"$cluster\",proto_name=\"S3Common\"}[$__rate_interval])",
       "legendFormat": "Write Latency"
      }
     ]
    },
    {
     "title": "S3 Protocol Error Rates",
     "type": "timeseries",
     "description": "These metrics are on a 5m interval. Internally VAST only updates these once every 5m.",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(vast_cluster_metrics_S3Metrics_cmd_errors{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "Unspecified Command Errors"
      },
      {
       "expr": "rate(vast_cluster_metrics_S3Metrics_cmd_not_supported{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "Unsupported Command"
      },
      {
       "expr": "rate(vast_cluster_metrics_S3Metrics_bad_http_request{cluster=\"$cluster\"}[$__rate_interval]) + rate(vast_cluster_metrics_S3Metrics_bad_https_request{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "Bad HTTP Requests"
      },
      {
       "expr": "rate(vast_cluster_metrics_ProtoConnectionMetrics_s3_conn_rejected{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "Rejected Connections"
      }
     ]
    },
    {
     "title": "S3 Object Request Rates",
     "type": "timeseries",
     "description": "These metrics are on a 5m interval. Internally VAST only updates these once every 5m.",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(vast_cluster_metrics_S3Metrics_get_object{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "GetObject Requests"
      },
      {
       "expr": "rate(vast_cluster_metrics_S3Metrics_put_object{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "PutObject Requests"
      },
      {
       "expr": "rate(vast_cluster_metrics_S3Metrics_multi_part_upload{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "Multi-Part Uploads"
      },
      {
       "expr": "rate(vast_cluster_metrics_S3Metrics_multi_part_upload_fallback{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "Multi-Part Upload Fallbacks"
      }
     ]
    },
    {
     "title": "S3 Metadata Rates",
     "type": "timeseries",
     "description": "These metrics are on a 5m interval. Internally VAST only updates these once every 5m.",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(vast_cluster_metrics_S3Metrics_get_service_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "GetService"
      },
      {
       "expr": "rate(vast_cluster_metrics_S3Metrics_get_bucket_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "GetBucket"
      },
      {
       "expr": "rate(vast_cluster_metrics_S3Metrics_get_bucket_location_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "GetBucketLocation"
      },
      {
       "expr": "rate(vast_cluster_metrics_S3Metrics_put_bucket_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "PutBucket"
      },
      {
       "expr": "rate(vast_cluster_metrics_S3Metrics_delete_bucket_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "DeleteBucket"
      },
      {
       "expr": "rate(vast_cluster_metrics_S3Metrics_head_bucket_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "HeadBucket"
      },
      {
       "expr": "rate(vast_cluster_metrics_S3Metrics_delete_object_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "DeleteObject"
      },
      {
       "expr": "rate(vast_cluster_metrics_S3Metrics_delete_objects_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "DeleteObjects"
      },
      {
       "expr": "rate(vast_cluster_metrics_S3Metrics_head_object_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "HeadObject"
      },
      {
       "expr": "rate(vast_cluster_metrics_S3Metrics_put_bucket_acl_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "PutBucketAcl"
      },
      {
       "expr": "rate(vast_cluster_metrics_S3Metrics_get_bucket_acl_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "GetBucketAcl"
      },
      {
       "expr": "rate(vast_cluster_metrics_S3Metrics_put_object_acl_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "PutObjecttAcl"
      },
      {
       "expr": "rate(vast_cluster_metrics_S3Metrics_get_object_acl_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "GetObjectAcl"
      },
      {
       "expr": "rate(vast_cluster_metrics_S3Metrics_put_object_copy_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "PutObjectCopy"
      },
      {
       "expr": "rate(vast_cluster_metrics_S3Metrics_initiate_mpu_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "CreateMultipartUpload"
      },
      {
       "expr": "rate(vast_cluster_metrics_S3Metrics_complete_mpu_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "CompleteMultipartUpload"
      }
     ]
    },
    {
     "title": "S3 Metadata Average Latencies",
     "type": "timeseries",
     "description": "These metrics are on a 5m interval. Internally VAST only updates these once every 5m.",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rate(vast_cluster_metrics_S3Metrics_get_service_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_S3Metrics_get_service_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "GetService"
      },
      {
       "expr": "rate(vast_cluster_metrics_S3Metrics_get_bucket_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_S3Metrics_get_bucket_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "GetBucket"
      },
      {
       "expr": "rate(vast_cluster_metrics_S3Metrics_get_bucket_location_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_S3Metrics_get_bucket_location_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "GetBucketLocation"
      },
      {
       "expr": "rate(vast_cluster_metrics_S3Metrics_put_bucket_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_S3Metrics_put_bucket_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "PutBucket"
      },
      {
       "expr": "rate(vast_cluster_metrics_S3Metrics_delete_bucket_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_S3Metrics_delete_bucket_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "DeleteBucket"
      },
      {
       "expr": "rate(vast_cluster_metrics_S3Metrics_head_bucket_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_S3Metrics_head_bucket_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "HeadBucket"
      },
      {
       "expr": "rate(vast_cluster_metrics_S3Metrics_delete_object_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_S3Metrics_delete_object_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "DeleteObject"
      },
      {
       "expr": "rate(vast_cluster_metrics_S3Metrics_delete_objects_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_S3Metrics_delete_objects_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "DeleteObjects"
      },
      {
       "expr": "rate(vast_cluster_metrics_S3Metrics_head_object_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_S3Metrics_head_object_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "HeadObject"
      },
      {
       "expr": "rate(vast_cluster_metrics_S3Metrics_put_bucket_acl_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_S3Metrics_put_bucket_acl_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "PutBucketAcl"
      },
      {
       "expr": "rate(vast_cluster_metrics_S3Metrics_get_bucket_acl_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_S3Metrics_get_bucket_acl_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "GetBucketAcl"
      },
      {
       "expr": "rate(vast_cluster_metrics_S3Metrics_put_object_acl_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_S3Metrics_put_object_acl_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "PutObjecttAcl"
      },
      {
       "expr": "rate(vast_cluster_metrics_S3Metrics_get_object_acl_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_S3Metrics_get_object_acl_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "GetObjectAcl"
      },
      {
       "expr": "rate(vast_cluster_metrics_S3Metrics_put_object_copy_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_S3Metrics_put_object_copy_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "PutObjectCopy"
      },
      {
       "expr": "rate(vast_cluster_metrics_S3Metrics_initiate_mpu_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_S3Metrics_initiate_mpu_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "CreateMultipartUpload"
      },
      {
       "expr": "rate(vast_cluster_metrics_S3Metrics_complete_mpu_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_S3Metrics_complete_mpu_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "CompleteMultipartUpload"
      }
     ]
    }
   ]
  },
  {
   "title": "S3 Metrics per Cnode",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Throughput for S3 per Cnode",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(vast_cnode_metrics_ProtoMetrics_read_size_sum{cluster=\"$cluster\",proto_name=\"S3Common\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - Read"
      },
      {
       "expr": "rate(vast_cnode_metrics_ProtoMetrics_write_size_sum{cluster=\"$cluster\",proto_name=\"S3Common\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - Write"
      }
     ]
    },
    {
     "title": "I/O Operations/sec for S3 per Cnode",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(vast_cnode_metrics_ProtoMetrics_read_size_count{cluster=\"$cluster\",proto_name=\"S3Common\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - Read"
      },
      {
       "expr": "rate(vast_cnode_metrics_ProtoMetrics_write_size_count{cluster=\"$cluster\",proto_name=\"S3Common\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - Write"
      },
      {
       "expr": "vast_cnode_metrics_ProtoMetrics_md_iops{cluster=\"$cluster\",proto_name=\"S3Common\"}",
       "legendFormat": "{{hostname}} - Other"
      }
     ]
    },
    {
     "title": "Average I/O Operation Size for S3",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(vast_cnode_metrics_ProtoMetrics_read_size_sum{cluster=\"$cluster\",proto_name=\"S3Common\"}[$__rate_interval]) / rate(vast_cnode_metrics_ProtoMetrics_read_size_count{cluster=\"$cluster\",proto_name=\"S3Common\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - Read"
      },
      {
       "expr": "rate(vast_cnode_metrics_ProtoMetrics_write_size_sum{cluster=\"$cluster\",proto_name=\"S3Common\"}[$__rate_interval]) / rate(vast_cnode_metrics_ProtoMetrics_write_size_count{cluster=\"$cluster\",proto_name=\"S3Common\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - Write"
      }
     ]
    },
    {
     "title": "Average I/O Latency for S3",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rate(vast_cnode_metrics_ProtoMetrics_read_latency_sum{cluster=\"$cluster\",proto_name=\"S3Common\"}[$__rate_interval]) / rate(vast_cnode_metrics_ProtoMetrics_read_latency_count{cluster=\"$cluster\",proto_name=\"S3Common\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - Read Latency"
      },
      {
       "expr": "rate(vast_cnode_metrics_ProtoMetrics_write_latency_sum{cluster=\"$cluster\",proto_name=\"S3Common\"}[$__rate_interval]) / rate(vast_cnode_metrics_ProtoMetrics_write_latency_count{cluster=\"$cluster\",proto_name=\"S3Common\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - Write Latency"
      }
     ]
    },
    {
     "title": "S3 Protocol Error Rates per Cnode",
     "type": "timeseries",
     "description": "These metrics are on a 5m interval. Internally VAST only updates these once every 5m.",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(vast_cnode_metrics_S3Metrics_cmd_errors{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - Unspecified Command Errors"
      },
      {
       "expr": "rate(vast_cnode_metrics_S3Metrics_cmd_not_supported{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - Unsupported Command"
      },
      {
       "expr": "rate(vast_cnode_metrics_S3Metrics_bad_http_request{cluster=\"$cluster\"}[$__rate_interval]) + rate(vast_cnode_metrics_S3Metrics_bad_https_request{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - Bad HTTP Requests"
      },
      {
       "expr": "rate(vast_cnode_metrics_ProtoConnectionMetrics_s3_conn_rejected{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - Rejected Connections"
      }
     ]
    },
    {
     "title": "S3 Object Request Rates per Cnode",
     "type": "timeseries",
     "description": "These metrics are on a 5m interval. Internally VAST only updates these once every 5m.",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(vast_cnode_metrics_S3Metrics_get_object{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - GetObject Requests"
      },
      {
       "expr": "rate(vast_cnode_metrics_S3Metrics_put_object{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - PutObject Requests"
      },
      {
       "expr": "rate(vast_cnode_metrics_S3Metrics_multi_part_upload{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - Multi-Part Uploads"
      },
      {
       "expr": "rate(vast_cnode_metrics_S3Metrics_multi_part_upload_fallback{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - Multi-Part Upload Fallbacks"
      }
     ]
    },
    {
     "title": "S3 Metadata Rates per Cnode",
     "type": "timeseries",
     "description": "These metrics are on a 5m interval. Internally VAST only updates these once every 5m.",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(vast_cnode_metrics_S3Metrics_get_service_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - GetService"
      },
      {
       "expr": "rate(vast_cnode_metrics_S3Metrics_get_bucket_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - GetBucket"
      },
      {
       "expr": "rate(vast_cnode_metrics_S3Metrics_get_bucket_location_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - GetBucketLocation"
      },
      {
       "expr": "rate(vast_cnode_metrics_S3Metrics_put_bucket_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - PutBucket"
      },
      {
       "expr": "rate(vast_cnode_metrics_S3Metrics_delete_bucket_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - DeleteBucket"
      },
      {
       "expr": "rate(vast_cnode_metrics_S3Metrics_head_bucket_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - HeadBucket"
      },
      {
       "expr": "rate(vast_cnode_metrics_S3Metrics_delete_object_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - DeleteObject"
      },
      {
       "expr": "rate(vast_cnode_metrics_S3Metrics_delete_objects_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - DeleteObjects"
      },
      {
       "expr": "rate(vast_cnode_metrics_S3Metrics_head_object_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - HeadObject"
      },
      {
       "expr": "rate(vast_cnode_metrics_S3Metrics_put_bucket_acl_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - PutBucketAcl"
      },
      {
       "expr": "rate(vast_cnode_metrics_S3Metrics_get_bucket_acl_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - GetBucketAcl"
      },
      {
       "expr": "rate(vast_cnode_metrics_S3Metrics_put_object_acl_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - PutObjecttAcl"
      },
      {
       "expr": "rate(vast_cnode_metrics_S3Metrics_get_object_acl_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - GetObjectAcl"
      },
      {
       "expr": "rate(vast_cnode_metrics_S3Metrics_put_object_copy_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - PutObjectCopy"
      },
      {
       "expr": "rate(vast_cnode_metrics_S3Metrics_initiate_mpu_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - CreateMultipartUpload"
      },
      {
       "expr": "rate(vast_cnode_metrics_S3Metrics_complete_mpu_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - CompleteMultipartUpload"
      }
     ]
    },
    {
     "title": "S3 Metadata Average Latencies per Cnode",
     "type": "timeseries",
     "description": "These metrics are on a 5m interval. Internally VAST only updates these once every 5m.",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rate(vast_cnode_metrics_S3Metrics_get_service_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cnode_metrics_S3Metrics_get_service_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - GetService"
      },
      {
       "expr": "rate(vast_cnode_metrics_S3Metrics_get_bucket_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cnode_metrics_S3Metrics_get_bucket_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - GetBucket"
      },
      {
       "expr": "rate(vast_cnode_metrics_S3Metrics_get_bucket_location_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cnode_metrics_S3Metrics_get_bucket_location_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - GetBucketLocation"
      },
      {
       "expr": "rate(vast_cnode_metrics_S3Metrics_put_bucket_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cnode_metrics_S3Metrics_put_bucket_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - PutBucket"
      },
      {
       "expr": "rate(vast_cnode_metrics_S3Metrics_delete_bucket_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cnode_metrics_S3Metrics_delete_bucket_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - DeleteBucket"
      },
      {
       "expr": "rate(vast_cnode_metrics_S3Metrics_head_bucket_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cnode_metrics_S3Metrics_head_bucket_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - HeadBucket"
      },
      {
       "expr": "rate(vast_cnode_metrics_S3Metrics_delete_object_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cnode_metrics_S3Metrics_delete_object_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - DeleteObject"
      },
      {
       "expr": "rate(vast_cnode_metrics_S3Metrics_delete_objects_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cnode_metrics_S3Metrics_delete_objects_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - DeleteObjects"
      },
      {
       "expr": "rate(vast_cnode_metrics_S3Metrics_head_object_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cnode_metrics_S3Metrics_head_object_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - HeadObject"
      },
      {
       "expr": "rate(vast_cnode_metrics_S3Metrics_put_bucket_acl_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cnode_metrics_S3Metrics_put_bucket_acl_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - PutBucketAcl"
      },
      {
       "expr": "rate(vast_cnode_metrics_S3Metrics_get_bucket_acl_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cnode_metrics_S3Metrics_get_bucket_acl_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - GetBucketAcl"
      },
      {
       "expr": "rate(vast_cnode_metrics_S3Metrics_put_object_acl_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cnode_metrics_S3Metrics_put_object_acl_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - PutObjecttAcl"
      },
      {
       "expr": "rate(vast_cnode_metrics_S3Metrics_get_object_acl_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cnode_metrics_S3Metrics_get_object_acl_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - GetObjectAcl"
      },
      {
       "expr": "rate(vast_cnode_metrics_S3Metrics_put_object_copy_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cnode_metrics_S3Metrics_put_object_copy_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - PutObjectCopy"
      },
      {
       "expr": "rate(vast_cnode_metrics_S3Metrics_initiate_mpu_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cnode_metrics_S3Metrics_initiate_mpu_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - CreateMultipartUpload"
      },
      {
       "expr": "rate(vast_cnode_metrics_S3Metrics_complete_mpu_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cnode_metrics_S3Metrics_complete_mpu_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} - CompleteMultipartUpload"
      }
     ]
    }
   ]
  },
  {
   "title": "NFS Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Throughput for NFS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(vast_cluster_metrics_ProtoMetrics_read_size_sum{cluster=\"$cluster\",proto_name=\"NFSCommon\"}[$__rate_interval])",
     "legendFormat": "Read"
    },
    {
     "expr": "rate(vast_cluster_metrics_ProtoMetrics_write_size_sum{cluster=\"$cluster\",proto_name=\"NFSCommon\"}[$__rate_interval])",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "I/O Operations/sec for NFS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(vast_cluster_metrics_ProtoMetrics_read_size_count{cluster=\"$cluster\",proto_name=\"NFSCommon\"}[$__rate_interval])",
     "legendFormat": "Reads"
    },
    {
     "expr": "rate(vast_cluster_metrics_ProtoMetrics_write_size_count{cluster=\"$cluster\",proto_name=\"NFSCommon\"}[$__rate_interval])",
     "legendFormat": "Writes"
    },
    {
     "expr": "vast_cluster_metrics_ProtoMetrics_md_iops{cluster=\"$cluster\",proto_name=\"NFSCommon\"}",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "Average I/O Operation Size for NFS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(vast_cluster_metrics_ProtoMetrics_read_size_sum{cluster=\"$cluster\",proto_name=\"NFSCommon\"}[$__rate_interval]) / rate(vast_cluster_metrics_ProtoMetrics_read_size_count{cluster=\"$cluster\",proto_name=\"NFSCommon\"}[$__rate_interval])",
     "legendFormat": "Read"
    },
    {
     "expr": "rate(vast_cluster_metrics_ProtoMetrics_write_size_sum{cluster=\"$cluster\",proto_name=\"NFSCommon\"}[$__rate_interval]) / rate(vast_cluster_metrics_ProtoMetrics_write_size_count{cluster=\"$cluster\",proto_name=\"NFSCommon\"}[$__rate_interval])",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Average I/O Latency for NFS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(vast_cluster_metrics_ProtoMetrics_read_latency_sum{cluster=\"$cluster\",proto_name=\"NFSCommon\"}[$__rate_interval]) / rate(vast_cluster_metrics_ProtoMetrics_read_latency_count{cluster=\"$cluster\",proto_name=\"NFSCommon\"}[$__rate_interval])",
     "legendFormat": "Read Latency"
    },
    {
     "expr": "rate(vast_cluster_metrics_ProtoMetrics_write_latency_sum{cluster=\"$cluster\",proto_name=\"NFSCommon\"}[$__rate_interval]) / rate(vast_cluster_metrics_ProtoMetrics_write_latency_count{cluster=\"$cluster\",proto_name=\"NFSCommon\"}[$__rate_interval])",
     "legendFormat": "Write Latency"
    }
   ]
  },
  {
   "title": "NFS Metadata Rates",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_create_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "create"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_mkdir_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "mkdir"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_mknod_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "mknod"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_symlink_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "symlink"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_setattr_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "setattr"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_remove_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "remove"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_rmdir_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "rmdir"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_rename_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "rename"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_link_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "link"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_commit_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "commit"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_getattr_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "getattr"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_lookup_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "lookup"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_access_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "access"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_readlink_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "readlink"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_readdir_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "readdir"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_readdirplus_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "readdirplus"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_fsstat_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "fsstat"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_fsinfo_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "fsinfo"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_pathconf_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "pathconf"
    }
   ]
  },
  {
   "title": "NFS Metadata Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_create_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_NfsMetrics_nfs_create_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "create"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_mkdir_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_NfsMetrics_nfs_mkdir_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "mkdir"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_mknod_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_NfsMetrics_nfs_mknod_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "mknod"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_symlink_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_NfsMetrics_nfs_symlink_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "symlink"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_setattr_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_NfsMetrics_nfs_setattr_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "setattr"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_remove_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_NfsMetrics_nfs_remove_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "remove"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_rmdir_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_NfsMetrics_nfs_rmdir_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "rmdir"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_rename_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_NfsMetrics_nfs_rename_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "rename"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_link_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_NfsMetrics_nfs_link_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "link"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_commit_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_NfsMetrics_nfs_commit_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "commit"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_getattr_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_NfsMetrics_nfs_getattr_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "getattr"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_lookup_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_NfsMetrics_nfs_lookup_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "lookup"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_access_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_NfsMetrics_nfs_access_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "access"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_readlink_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_NfsMetrics_nfs_readlink_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "readlink"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_readdir_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_NfsMetrics_nfs_readdir_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "readdir"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_readdirplus_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_NfsMetrics_nfs_readdirplus_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "readdirplus"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_fsstat_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_NfsMetrics_nfs_fsstat_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "fsstat"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_fsinfo_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_NfsMetrics_nfs_fsinfo_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "fsinfo"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_pathconf_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_NfsMetrics_nfs_pathconf_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "pathconf"
    }
   ]
  },
  {
   "title": "NFS Metrics per Cnode",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Throughput for NFS per Cnode",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(vast_cnode_metrics_ProtoMetrics_read_size_sum{cluster=\"$cluster\",proto_name=\"NFSCommon\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - Read"
    },
    {
     "expr": "rate(vast_cnode_metrics_ProtoMetrics_write_size_sum{cluster=\"$cluster\",proto_name=\"NFSCommon\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - Write"
    }
   ]
  },
  {
   "title": "I/O Operations/sec for NFS per Cnode",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(vast_cnode_metrics_ProtoMetrics_read_size_count{cluster=\"$cluster\",proto_name=\"NFSCommon\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - Reads"
    },
    {
     "expr": "rate(vast_cnode_metrics_ProtoMetrics_write_size_count{cluster=\"$cluster\",proto_name=\"NFSCommon\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - Writes"
    },
    {
     "expr": "vast_cnode_metrics_ProtoMetrics_md_iops{cluster=\"$cluster\",proto_name=\"NFSCommon\"}",
     "legendFormat": "{{hostname}} - Other"
    }
   ]
  },
  {
   "title": "Average I/O Operation Size for NFS per Cnode",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(vast_cnode_metrics_ProtoMetrics_read_size_sum{cluster=\"$cluster\",proto_name=\"NFSCommon\"}[$__rate_interval]) / rate(vast_cnode_metrics_ProtoMetrics_read_size_count{cluster=\"$cluster\",proto_name=\"NFSCommon\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - Read"
    },
    {
     "expr": "rate(vast_cnode_metrics_ProtoMetrics_write_size_sum{cluster=\"$cluster\",proto_name=\"NFSCommon\"}[$__rate_interval]) / rate(vast_cnode_metrics_ProtoMetrics_write_size_count{cluster=\"$cluster\",proto_name=\"NFSCommon\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - Write"
    }
   ]
  },
  {
   "title": "Average I/O Latency for NFS per Cnode",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(vast_cnode_metrics_ProtoMetrics_read_latency_sum{cluster=\"$cluster\",proto_name=\"NFSCommon\"}[$__rate_interval]) / rate(vast_cnode_metrics_ProtoMetrics_read_latency_count{cluster=\"$cluster\",proto_name=\"NFSCommon\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - Read Latency"
    },
    {
     "expr": "rate(vast_cnode_metrics_ProtoMetrics_write_latency_sum{cluster=\"$cluster\",proto_name=\"NFSCommon\"}[$__rate_interval]) / rate(vast_cnode_metrics_ProtoMetrics_write_latency_count{cluster=\"$cluster\",proto_name=\"NFSCommon\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - Write Latency"
    }
   ]
  },
  {
   "title": "NFS Metadata Rates per Cnode",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(vast_cnode_metrics_NfsMetrics_nfs_create_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - create"
    },
    {
     "expr": "rate(vast_cnode_metrics_NfsMetrics_nfs_mkdir_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - mkdir"
    },
    {
     "expr": "rate(vast_cnode_metrics_NfsMetrics_nfs_mknod_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - mknod"
    },
    {
     "expr": "rate(vast_cnode_metrics_NfsMetrics_nfs_symlink_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - symlink"
    },
    {
     "expr": "rate(vast_cnode_metrics_NfsMetrics_nfs_setattr_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - setattr"
    },
    {
     "expr": "rate(vast_cnode_metrics_NfsMetrics_nfs_remove_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - remove"
    },
    {
     "expr": "rate(vast_cnode_metrics_NfsMetrics_nfs_rmdir_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - rmdir"
    },
    {
     "expr": "rate(vast_cnode_metrics_NfsMetrics_nfs_rename_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - rename"
    },
    {
     "expr": "rate(vast_cnode_metrics_NfsMetrics_nfs_link_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - link"
    },
    {
     "expr": "rate(vast_cnode_metrics_NfsMetrics_nfs_commit_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - commit"
    },
    {
     "expr": "rate(vast_cnode_metrics_NfsMetrics_nfs_getattr_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - getattr"
    },
    {
     "expr": "rate(vast_cnode_metrics_NfsMetrics_nfs_lookup_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - lookup"
    },
    {
     "expr": "rate(vast_cnode_metrics_NfsMetrics_nfs_access_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - access"
    },
    {
     "expr": "rate(vast_cnode_metrics_NfsMetrics_nfs_readlink_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - readlink"
    },
    {
     "expr": "rate(vast_cnode_metrics_NfsMetrics_nfs_readdir_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - readdir"
    },
    {
     "expr": "rate(vast_cnode_metrics_NfsMetrics_nfs_readdirplus_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - readdirplus"
    },
    {
     "expr": "rate(vast_cnode_metrics_NfsMetrics_nfs_fsstat_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - fsstat"
    },
    {
     "expr": "rate(vast_cnode_metrics_NfsMetrics_nfs_fsinfo_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - fsinfo"
    },
    {
     "expr": "rate(vast_cnode_metrics_NfsMetrics_nfs_pathconf_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - pathconf"
    }
   ]
  },
  {
   "title": "NFS Metadata Latency per Cnode",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(vast_cnode_metrics_NfsMetrics_nfs_create_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cnode_metrics_NfsMetrics_nfs_create_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - create"
    },
    {
     "expr": "rate(vast_cnode_metrics_NfsMetrics_nfs_mkdir_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cnode_metrics_NfsMetrics_nfs_mkdir_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - mkdir"
    },
    {
     "expr": "rate(vast_cnode_metrics_NfsMetrics_nfs_mknod_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cnode_metrics_NfsMetrics_nfs_mknod_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - mknod"
    },
    {
     "expr": "rate(vast_cnode_metrics_NfsMetrics_nfs_symlink_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cnode_metrics_NfsMetrics_nfs_symlink_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - symlink"
    },
    {
     "expr": "rate(vast_cnode_metrics_NfsMetrics_nfs_setattr_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cnode_metrics_NfsMetrics_nfs_setattr_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - setattr"
    },
    {
     "expr": "rate(vast_cnode_metrics_NfsMetrics_nfs_remove_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cnode_metrics_NfsMetrics_nfs_remove_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - remove"
    },
    {
     "expr": "rate(vast_cnode_metrics_NfsMetrics_nfs_rmdir_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cnode_metrics_NfsMetrics_nfs_rmdir_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - rmdir"
    },
    {
     "expr": "rate(vast_cnode_metrics_NfsMetrics_nfs_rename_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cnode_metrics_NfsMetrics_nfs_rename_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - rename"
    },
    {
     "expr": "rate(vast_cnode_metrics_NfsMetrics_nfs_link_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cnode_metrics_NfsMetrics_nfs_link_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - link"
    },
    {
     "expr": "rate(vast_cnode_metrics_NfsMetrics_nfs_commit_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cnode_metrics_NfsMetrics_nfs_commit_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - commit"
    },
    {
     "expr": "rate(vast_cnode_metrics_NfsMetrics_nfs_getattr_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cnode_metrics_NfsMetrics_nfs_getattr_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - getattr"
    },
    {
     "expr": "rate(vast_cnode_metrics_NfsMetrics_nfs_lookup_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cnode_metrics_NfsMetrics_nfs_lookup_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - lookup"
    },
    {
     "expr": "rate(vast_cnode_metrics_NfsMetrics_nfs_access_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cnode_metrics_NfsMetrics_nfs_access_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - access"
    },
    {
     "expr": "rate(vast_cnode_metrics_NfsMetrics_nfs_readlink_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cnode_metrics_NfsMetrics_nfs_readlink_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - readlink"
    },
    {
     "expr": "rate(vast_cnode_metrics_NfsMetrics_nfs_readdir_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cnode_metrics_NfsMetrics_nfs_readdir_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - readdir"
    },
    {
     "expr": "rate(vast_cnode_metrics_NfsMetrics_nfs_readdirplus_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cnode_metrics_NfsMetrics_nfs_readdirplus_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - readdirplus"
    },
    {
     "expr": "rate(vast_cnode_metrics_NfsMetrics_nfs_fsstat_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cnode_metrics_NfsMetrics_nfs_fsstat_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - fsstat"
    },
    {
     "expr": "rate(vast_cnode_metrics_NfsMetrics_nfs_fsinfo_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cnode_metrics_NfsMetrics_nfs_fsinfo_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - fsinfo"
    },
    {
     "expr": "rate(vast_cnode_metrics_NfsMetrics_nfs_pathconf_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cnode_metrics_NfsMetrics_nfs_pathconf_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - pathconf"
    }
   ]
  },
  {
   "title": "View Metrics: $view",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "repeat": "view",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$view - I/O Operations/sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "vast_view_read_iops{cluster=\"$cluster\",path=\"$view\"} OR on() vector(0)",
       "legendFormat": "$view - Read"
      },
      {
       "expr": "vast_view_write_iops{cluster=\"$cluster\",path=\"$view\"} OR on() vector(0)",
       "legendFormat": "$view - Write"
      },
      {
       "expr": "vast_view_md_iops{cluster=\"$cluster\",path=\"$view\"} OR on() vector(0)",
       "legendFormat": "$view - Other"
      }
     ]
    },
    {
     "title": "$view - Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "vast_view_read_bw{cluster=\"$cluster\",path=\"$view\"} OR on() vector(0)",
       "legendFormat": "$view - Read"
      },
      {
       "expr": "vast_view_write_bw{cluster=\"$cluster\",path=\"$view\"} OR on() vector(0)",
       "legendFormat": "$view - Write"
      }
     ]
    },
    {
     "title": "$view Capacity Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "vast_view_physical_capacity{cluster=\"$cluster\",name!=\"root\",path=\"$view\"}",
       "legendFormat": "{{path}} - Physical Used"
      },
      {
       "expr": "vast_view_logical_capacity{cluster=\"$cluster\",name!=\"root\",path=\"$view\"}",
       "legendFormat": "{{path}} - Logical Used"
      }
     ]
    },
    {
     "title": "$view - Data Reduction Ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "vast_view_logical_capacity{cluster=\"$cluster\",name!=\"root\",path=\"$view\"} / vast_view_physical_capacity{cluster=\"$cluster\",name!=\"root\",path=\"$view\"}",
       "legendFormat": "{{path}} - Data Reduction Ratio"
      }
     ]
    },
    {
     "title": "$view - Rate of Change",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "delta(vast_view_physical_capacity{cluster=\"$cluster\",path=\"$view\"}[5m])",
       "legendFormat": "{{path}} - 5m Rate of Change"
      }
     ]
    }
   ]
  },
  {
   "title": "NVRAM/SSD Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 165 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Throughput per NVRAM drive",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "expr": "vast_nvram_metrics_Hardware_r_mbs{cluster=\"$cluster\"}",
       "legendFormat": "{{title}} - Read"
      },
      {
       "expr": "vast_nvram_metrics_Hardware_w_mbs{cluster=\"$cluster\"}",
       "legendFormat": "{{title}} - Write"
      }
     ]
    },
    {
     "title": "IOPs per NVRAM device",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(vast_nvram_metrics_Hardware_write_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{title}} - Write"
      },
      {
       "expr": "rate(vast_nvram_metrics_Hardware_read_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{title}} - Read"
      }
     ]
    },
    {
     "title": "Latency per NVRAM device",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "vast_nvram_metrics_Hardware_r_await{cluster=\"$cluster\"}",
       "legendFormat": "{{title}} - Read Latency"
      },
      {
       "expr": "vast_nvram_metrics_Hardware_w_await{cluster=\"$cluster\"}",
       "legendFormat": "{{title}} - Write Latency"
      }
     ]
    },
    {
     "title": "Throughput per SSD drive",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "expr": "vast_ssd_metrics_Hardware_w_mbs{cluster=\"$cluster\"}",
       "legendFormat": "{{title}} - Write"
      },
      {
       "expr": "vast_ssd_metrics_Hardware_r_mbs{cluster=\"$cluster\"}",
       "legendFormat": "{{title}} - Read"
      }
     ]
    },
    {
     "title": "IOPs per SSD device",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(vast_ssd_metrics_Hardware_write_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{title}} - Write"
      },
      {
       "expr": "rate(vast_ssd_metrics_Hardware_read_count{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{title}} - Read"
      }
     ]
    },
    {
     "title": "Latency per SSD device",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "vast_ssd_metrics_Hardware_r_await{cluster=\"$cluster\"}",
       "legendFormat": "{{title}} - Read Latency"
      },
      {
       "expr": "vast_ssd_metrics_Hardware_w_await{cluster=\"$cluster\"}",
       "legendFormat": "{{title}} - Write Latency"
      }
     ]
    },
    {
     "title": "Media Errors",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "vast_nvram_metrics_Hardware_media_errors{cluster=\"$cluster\"} OR vast_ssd_metrics_Hardware_media_errors{cluster=\"$cluster\"}",
       "legendFormat": "{{title}} - Errors"
      }
     ]
    },
    {
     "title": "Drive Endurance Remaining",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "vast_nvram_metrics_Hardware_endurance{cluster=\"$cluster\"} OR vast_ssd_metrics_Hardware_endurance{cluster=\"$cluster\"}",
       "legendFormat": "{{title}}"
      }
     ]
    },
    {
     "title": "Drive Temperature",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "vast_nvram_metrics_Hardware_temperature{cluster=\"$cluster\"} OR vast_ssd_metrics_Hardware_temperature{cluster=\"$cluster\"}",
       "legendFormat": "{{title}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Hardware Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 166 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Hardware Temperatures",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "vast_cnode_metrics_Hardware_cpu_temp{cluster=\"$cluster\"}",
       "legendFormat": "{{hostname}} CPU Temperature"
      }
     ]
    },
    {
     "title": "NIC Errors",
     "type": "timeseries",
     "description": "Items will only appear here if non-zero due to the number of metrics involved.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(vast_nic_metrics_Hardware_rx_buff_alloc_err{cluster=\"$cluster\"}[$__rate_interval]) != 0",
       "legendFormat": "{{hostname}} - {{display_name}} - RX Buffer Allocation Errors"
      },
      {
       "expr": "rate(vast_nic_metrics_Hardware_rx_crc_errors_phy{cluster=\"$cluster\"}[$__rate_interval]) != 0",
       "legendFormat": "{{hostname}} - {{display_name}} - RX CRC Errors"
      },
      {
       "expr": "rate(vast_nic_metrics_Hardware_rx_errors{cluster=\"$cluster\"}[$__rate_interval]) != 0",
       "legendFormat": "{{hostname}} - {{display_name}} - RX Errors"
      },
      {
       "expr": "rate(vast_nic_metrics_Hardware_rx_in_range_len_errors_phy{cluster=\"$cluster\"}[$__rate_interval]) != 0",
       "legendFormat": "{{hostname}} - {{display_name}} - RX Range Length Errors"
      },
      {
       "expr": "rate(vast_nic_metrics_Hardware_rx_symbol_err_phy{cluster=\"$cluster\"}[$__rate_interval]) != 0",
       "legendFormat": "{{hostname}} - {{display_name}} - RX Symbol Errors"
      },
      {
       "expr": "rate(vast_nic_metrics_Hardware_tx_errors{cluster=\"$cluster\"}[$__rate_interval]) != 0",
       "legendFormat": "{{hostname}} - {{display_name}} - TX Errors"
      },
      {
       "expr": "rate(vast_nic_metrics_Hardware_tx_errors_phy{cluster=\"$cluster\"}[$__rate_interval]) != 0",
       "legendFormat": "{{hostname}} - {{display_name}} - TX Errors Phy"
      }
     ]
    }
   ]
  }
 ]
}